# Generated by Django 2.1.15 on 2021-10-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='max_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='space',
            name='min_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
